# Generated by Django 3.2 on 2021-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountUrl', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='', max_length=255, null=True)),
                ('level', models.CharField(max_length=2)),
            ],
        ),
    ]
